
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jul 11 15:50:25 PDT 2004
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 18;
  public static final int TIMES = 6;
  public static final int LT = 10;
  public static final int ELSE = 25;
  public static final int PLUS = 4;
  public static final int NOTEQ = 14;
  public static final int INT = 21;
  public static final int RBRACE = 20;
  public static final int RPAREN = 16;
  public static final int WHILE = 24;
  public static final int SEMI = 2;
  public static final int LBRACK = 17;
  public static final int RETURN = 26;
  public static final int IF = 23;
  public static final int LBRACE = 19;
  public static final int LPAREN = 15;
  public static final int GT = 11;
  public static final int ID = 28;
  public static final int COMMA = 3;
  public static final int LTEQ = 9;
  public static final int NUMBER = 27;
  public static final int EOF = 0;
  public static final int DIVIDE = 7;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int EQ = 8;
  public static final int GTEQ = 12;
  public static final int EQEQ = 13;
  public static final int VOID = 22;
}

